In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("full.csv", index_col=False)

In [3]:
df

,accuracy,kappa,testName,anchorMethod,numAnchors,silBoost
0,0.750000,0.152318,emily_embeddings.tsv,FIXED,1,0.0
1,0.750000,0.152318,emily_embeddings.tsv,DRIFT,1,0.0
2,0.750000,0.152318,emily_embeddings.tsv,FIXED,1,1.4
3,0.750000,0.152318,emily_embeddings.tsv,DRIFT,1,1.4
4,0.500000,0.055351,emily_embeddings.tsv,FIXED,2,0.0
...,...,...,...,...,...,...
4127,0.787234,0.132841,greg_embeddings.tsv,DRIFT,2,1.4
4128,0.787234,0.132841,greg_embeddings.tsv,FIXED,3,0.0
4129,0.744681,0.107595,greg_embeddings.tsv,DRIFT,3,0.0
4130,0.787234,0.132841,greg_embeddings.tsv,FIXED,3,1.4
4131,0.744681,0.107595,greg_embeddings.tsv,DRIFT,3,1.4

In [4]:
df[df.numAnchors == 3].groupby(["anchorMethod"]).mean()

/var/folders/jq/lt0dyzf14y93d8k18k68_4fm0000gn/T/ipykernel_90551/1687026169.py:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df[df.numAnchors == 3].groupby(["anchorMethod"]).mean()

              accuracy     kappa  numAnchors  silBoost
anchorMethod
DRIFT         0.709526  0.075073         3.0  0.698984
FIXED         0.802391  0.116437         3.0  0.698984

In [5]:
df[df.numAnchors == 1].groupby(["anchorMethod"]).mean()

/var/folders/jq/lt0dyzf14y93d8k18k68_4fm0000gn/T/ipykernel_90551/4054225228.py:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df[df.numAnchors == 1].groupby(["anchorMethod"]).mean()

              accuracy     kappa  numAnchors  silBoost
anchorMethod
DRIFT         0.841783  0.133174         1.0       0.7
FIXED         0.856031  0.150774         1.0       0.7

In [6]:
df.groupby(["anchorMethod"]).mean()

/var/folders/jq/lt0dyzf14y93d8k18k68_4fm0000gn/T/ipykernel_90551/3579786468.py:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df.groupby(["anchorMethod"]).mean()

              accuracy     kappa  numAnchors  silBoost
anchorMethod
DRIFT         0.761772  0.094499    2.000484       0.7
FIXED         0.819637  0.130391    2.000484       0.7

In [13]:
!pwd

/Users/Rrando/Documents/GitHub/content-ml-experiments/tab_grouping/analysis

In [5]:
all_pipeline = pd.read_csv("./all_pipeline.csv", index_col=False)

In [6]:
all_pipeline.groupby(["clustering_method", "tf_idf_scale", "remap", "dbscan_eps"]).mean().sort_values(["adj_rand"], ascending=False)

/var/folders/jq/lt0dyzf14y93d8k18k68_4fm0000gn/T/ipykernel_31550/2563808502.py:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  all_pipeline.groupby(["clustering_method", "tf_idf_scale", "remap", "dbscan_eps"]).mean().sort_values(["adj_rand"], ascending=False)

                                                 Unnamed: 0  history_scale  \
clustering_method tf_idf_scale remap dbscan_eps
dbscan            0.3          5     0.3             1339.0            0.0
                                     0.4             1351.0            0.0
                  0.2          5     0.5             1362.0            0.0
                  0.3          5     0.5             1363.0            0.0
                  0.0          5     0.3             1336.0            0.0
                                     0.4             1348.0            0.0
                  0.2          5     0.3             1338.0            0.0
                  0.1          5     0.5             1361.0            0.0
kmeans            0.3          15    0.4             1331.0            0.0
dbscan            0.1          5     0.3             1337.0            0.0
kmeans            0.0          15    0.4             1328.0            0.0
dbscan            0.0          5     0.5             1360.0            0.0
                  0.1          5     0.4             1349.0            0.0
                  0.2          5     0.4             1350.0            0.0
kmeans            0.2          5     0.4             1326.0            0.0
                               15    0.4             1330.0            0.0
                  0.1          15    0.4             1329.0            0.0
                  0.3          5     0.4             1327.0            0.0
                  0.1          5     0.4             1325.0            0.0
dbscan            0.3          15    0.4             1355.0            0.0
kmeans            0.0          5     0.4             1324.0            0.0
dbscan            0.2          15    0.3             1342.0            0.0
                                     0.4             1354.0            0.0
                  0.0          15    0.5             1364.0            0.0
                  0.1          15    0.5             1365.0            0.0
                                     0.4             1353.0            0.0
                  0.0          15    0.4             1352.0            0.0
                  0.3          15    0.5             1367.0            0.0
                  0.0          15    0.3             1340.0            0.0
                  0.2          15    0.5             1366.0            0.0
                  0.1          15    0.3             1341.0            0.0
                  0.3          15    0.3             1343.0            0.0
kmeans            0.2          0     0.4             1322.0            0.0
                  0.0          0     0.4             1320.0            0.0
                  0.3          0     0.4             1323.0            0.0
                  0.1          0     0.4             1321.0            0.0
dbscan            0.0          0     0.5             1356.0            0.0
                                     0.4             1344.0            0.0
                  0.1          0     0.4             1345.0            0.0
                                     0.3             1333.0            0.0
                                     0.5             1357.0            0.0
                  0.3          0     0.3             1335.0            0.0
                  0.0          0     0.3             1332.0            0.0
                  0.3          0     0.4             1347.0            0.0
                  0.2          0     0.3             1334.0            0.0
                                     0.5             1358.0            0.0
                                     0.4             1346.0            0.0
                  0.3          0     0.5             1359.0            0.0

                                                 domain_scale  \
clustering_method tf_idf_scale remap dbscan_eps
dbscan            0.3          5     0.3                  0.0
                                     0.4                  0.0
                  0.2          5     0.5                  0.0
                  0.3          5     0.5                  0.0
                  0.0          5     0.3                  0.0
                                     0.4                  0.0
                  0.2          5     0.3                  0.0
                  0.1          5     0.5                  0.0
kmeans            0.3          15    0.4                  0.0
dbscan            0.1          5     0.3                  0.0
kmeans            0.0          15    0.4                  0.0
dbscan            0.0          5     0.5                  0.0
                  0.1          5     0.4                  0.0
                  0.2          5     0.4                  0.0
kmeans            0.2          5     0.4                  0.0
                               15    0.4                  0.0
                  0.1          15    0.4                  0.0
                  0.3          5     0.4                  0.0
                  0.1          5     0.4                  0.0
dbscan            0.3          15    0.4                  0.0
kmeans            0.0          5     0.4                  0.0
dbscan            0.2          15    0.3                  0.0
                                     0.4                  0.0
                  0.0          15    0.5                  0.0
                  0.1          15    0.5                  0.0
                                     0.4                  0.0
                  0.0          15    0.4                  0.0
                  0.3          15    0.5                  0.0
                  0.0          15    0.3                  0.0
                  0.2          15    0.5                  0.0
                  0.1          15    0.3                  0.0
                  0.3          15    0.3                  0.0
kmeans            0.2          0     0.4                  0.0
                  0.0          0     0.4                  0.0
                  0.3          0     0.4                  0.0
                  0.1          0     0.4                  0.0
dbscan            0.0          0     0.5                  0.0
                                     0.4                  0.0
                  0.1          0     0.4                  0.0
                                     0.3                  0.0
                                     0.5                  0.0
                  0.3          0     0.3                  0.0
                  0.0          0     0.3                  0.0
                  0.3          0     0.4                  0.0
                  0.2          0     0.3                  0.0
                                     0.5                  0.0
                                     0.4                  0.0
                  0.3          0     0.5                  0.0

                                                 title_embedding_scale  \
clustering_method tf_idf_scale remap dbscan_eps
dbscan            0.3          5     0.3                           1.0
                                     0.4                           1.0
                  0.2          5     0.5                           1.0
                  0.3          5     0.5                           1.0
                  0.0          5     0.3                           1.0
                                     0.4                           1.0
                  0.2          5     0.3                           1.0
                  0.1          5     0.5                           1.0
kmeans            0.3          15    0.4                           1.0
dbscan            0.1          5     0.3                           1.0
kmeans            0.0          15    0.4                           1.0
dbscan            0.0          5     0.5                           1.0
                  0.1          5     0.4                           1.0
                  0.2          5     0.4                           1.0
kmeans            0.2          5     0.4                           1.0
                               15    0.4                           1.0
                  0.1          15    0.4                           1.0
                  0.3          5     0.4                           1.0
                  0.1          5     0.4                           1.0
dbscan            0.3          15    0.4                           1.0
kmeans            0.0          5     0.4                           1.0
dbscan            0.2          15    0.3                           1.0
                                     0.4                           1.0
                  0.0          15    0.5                           1.0
                  0.1          15    0.5                           1.0
                                     0.4                           1.0
                  0.0          15    0.4                           1.0
                  0.3          15    0.5                           1.0
                  0.0          15    0.3                           1.0
                  0.2          15    0.5                           1.0
                  0.1          15    0.3                           1.0
                  0.3          15    0.3                           1.0
kmeans            0.2          0     0.4                           1.0
                  0.0          0     0.4                           1.0
                  0.3          0     0.4                           1.0
                  0.1          0     0.4                           1.0
dbscan            0.0          0     0.5                           1.0
                                     0.4                           1.0
                  0.1          0     0.4                           1.0
                                     0.3                           1.0
                                     0.5                           1.0
                  0.3          0     0.3                           1.0
                  0.0          0     0.3                           1.0
                  0.3          0     0.4                           1.0
                  0.2          0     0.3                           1.0
                                     0.5                           1.0
                                     0.4                           1.0
                  0.3          0     0.5                           1.0

                                                     rand  adj_rand
clustering_method tf_idf_scale remap dbscan_eps
dbscan            0.3          5     0.3         0.800872  0.364023
                                     0.4         0.794772  0.359055
                  0.2          5     0.5         0.791034  0.354760
                  0.3          5     0.5         0.799238  0.353957
                  0.0          5     0.3         0.793770  0.351563
                                     0.4         0.794378  0.347898
                  0.2          5     0.3         0.789821  0.345792
                  0.1          5     0.5         0.779388  0.340374
kmeans            0.3          15    0.4         0.743813  0.338441
dbscan            0.1          5     0.3         0.785502  0.337431
kmeans            0.0          15    0.4         0.745420  0.337181
dbscan            0.0          5     0.5         0.785785  0.333402
                  0.1          5     0.4         0.782962  0.331806
                  0.2          5     0.4         0.785774  0.330820
kmeans            0.2          5     0.4         0.732529  0.330662
                               15    0.4         0.738883  0.325336
                  0.1          15    0.4         0.742208  0.321906
                  0.3          5     0.4         0.726770  0.318727
                  0.1          5     0.4         0.724333  0.312570
dbscan            0.3          15    0.4         0.740527  0.301732
kmeans            0.0          5     0.4         0.713306  0.299799
dbscan            0.2          15    0.3         0.739612  0.294205
                                     0.4         0.734766  0.289947
                  0.0          15    0.5         0.723007  0.288268
                  0.1          15    0.5         0.729160  0.287763
                                     0.4         0.727874  0.287064
                  0.0          15    0.4         0.721996  0.285680
                  0.3          15    0.5         0.730880  0.285333
                  0.0          15    0.3         0.720039  0.283822
                  0.2          15    0.5         0.735079  0.283759
                  0.1          15    0.3         0.732180  0.279688
                  0.3          15    0.3         0.728520  0.279203
kmeans            0.2          0     0.4         0.735445  0.277878
                  0.0          0     0.4         0.730139  0.277629
                  0.3          0     0.4         0.727076  0.276215
                  0.1          0     0.4         0.727747  0.271124
dbscan            0.0          0     0.5         0.689179  0.256568
                                     0.4         0.687786  0.255828
                  0.1          0     0.4         0.686185  0.255206
                                     0.3         0.685546  0.254895
                                     0.5         0.687280  0.254833
                  0.3          0     0.3         0.681074  0.252954
                  0.0          0     0.3         0.684678  0.252189
                  0.3          0     0.4         0.676580  0.249847
                  0.2          0     0.3         0.681268  0.249763
                                     0.5         0.684657  0.249597
                                     0.4         0.681162  0.249232
                  0.3          0     0.5         0.671968  0.245342

In [38]:
all_pipeline.groupby(["clustering_method", "tf_idf_scale", "remap", "dbscan_eps"]).mean().sort_values(["adj_rand"], ascending=False).to_csv("sorted.csv")

/var/folders/jq/lt0dyzf14y93d8k18k68_4fm0000gn/T/ipykernel_90551/1993900622.py:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  all_pipeline.groupby(["clustering_method", "tf_idf_scale", "remap", "dbscan_eps"]).mean().sort_values(["adj_rand"], ascending=False).to_csv("sorted.csv")

In [29]:
all_pipeline[(all_pipeline.clustering_method == "dbscan") & (all_pipeline.remap == 5)].groupby(["dbscan_eps"]).mean().sort_values(["adj_rand"], ascending=False)

/var/folders/jq/lt0dyzf14y93d8k18k68_4fm0000gn/T/ipykernel_90551/2903459063.py:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  all_pipeline[(all_pipeline.clustering_method == "dbscan") & (all_pipeline.remap == 5)].groupby(["dbscan_eps"]).mean().sort_values(["adj_rand"], ascending=False)

,Unnamed: 0,history_scale,domain_scale,title_embedding_scale,tf_idf_scale,remap,rand,adj_rand
dbscan_eps,,,,,,,,
0.3,1337.5,0.0,0.0,1.0,0.15,5.0,0.792492,0.349702
0.5,1361.5,0.0,0.0,1.0,0.15,5.0,0.788861,0.345623
0.4,1349.5,0.0,0.0,1.0,0.15,5.0,0.789472,0.342395

In [31]:
all_pipeline[(all_pipeline.clustering_method == "dbscan") & (all_pipeline.remap == 5)].groupby(["tf_idf_scale"]).mean().sort_values(["adj_rand"], ascending=False)

/var/folders/jq/lt0dyzf14y93d8k18k68_4fm0000gn/T/ipykernel_90551/747050292.py:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  all_pipeline[(all_pipeline.clustering_method == "dbscan") & (all_pipeline.remap == 5)].groupby(["tf_idf_scale"]).mean().sort_values(["adj_rand"], ascending=False)

,Unnamed: 0,history_scale,domain_scale,title_embedding_scale,dbscan_eps,remap,rand,adj_rand
tf_idf_scale,,,,,,,,
0.3,1351.0,0.0,0.0,1.0,0.4,5.0,0.798294,0.359011
0.0,1348.0,0.0,0.0,1.0,0.4,5.0,0.791311,0.344288
0.2,1350.0,0.0,0.0,1.0,0.4,5.0,0.788877,0.343791
0.1,1349.0,0.0,0.0,1.0,0.4,5.0,0.782618,0.336537

In [37]:
all_pipeline.drop("rand", axis=1).corr()['adj_rand']

/var/folders/jq/lt0dyzf14y93d8k18k68_4fm0000gn/T/ipykernel_90551/4044017682.py:1: FutureWarning: The default value of numeric_only in DataFrame.corr is deprecated. In a future version, it will default to False. Select only valid columns or specify the value of numeric_only to silence this warning.
  all_pipeline.drop("rand", axis=1).corr()['adj_rand']

Unnamed: 0              -0.128952
history_scale                 NaN
domain_scale                  NaN
title_embedding_scale         NaN
tf_idf_scale             0.009312
dbscan_eps              -0.001607
remap                    0.050316
adj_rand                 1.000000
Name: adj_rand, dtype: float64

In [11]:
all_pipeline[(all_pipeline.remap == 0) & (all_pipeline.dbscan_eps == 0.4)].groupby(["clustering_method", "tf_idf_scale"]).mean().sort_values(["adj_rand"], ascending=False)

/var/folders/jq/lt0dyzf14y93d8k18k68_4fm0000gn/T/ipykernel_31550/1101770099.py:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  all_pipeline[(all_pipeline.remap == 0) & (all_pipeline.dbscan_eps == 0.4)].groupby(["clustering_method", "tf_idf_scale"]).mean().sort_values(["adj_rand"], ascending=False)

                                Unnamed: 0  history_scale  domain_scale  \
clustering_method tf_idf_scale
kmeans            0.2               1322.0            0.0           0.0
                  0.0               1320.0            0.0           0.0
                  0.3               1323.0            0.0           0.0
                  0.1               1321.0            0.0           0.0
dbscan            0.0               1344.0            0.0           0.0
                  0.1               1345.0            0.0           0.0
                  0.3               1347.0            0.0           0.0
                  0.2               1346.0            0.0           0.0

                                title_embedding_scale  dbscan_eps  remap  \
clustering_method tf_idf_scale
kmeans            0.2                             1.0         0.4    0.0
                  0.0                             1.0         0.4    0.0
                  0.3                             1.0         0.4    0.0
                  0.1                             1.0         0.4    0.0
dbscan            0.0                             1.0         0.4    0.0
                  0.1                             1.0         0.4    0.0
                  0.3                             1.0         0.4    0.0
                  0.2                             1.0         0.4    0.0

                                    rand  adj_rand
clustering_method tf_idf_scale
kmeans            0.2           0.735445  0.277878
                  0.0           0.730139  0.277629
                  0.3           0.727076  0.276215
                  0.1           0.727747  0.271124
dbscan            0.0           0.687786  0.255828
                  0.1           0.686185  0.255206
                  0.3           0.676580  0.249847
                  0.2           0.681162  0.249232

In [12]:
all_pipeline[(all_pipeline.remap == 0) & (all_pipeline.dbscan_eps == 0.4)].groupby(["clustering_method", "tf_idf_scale"]).mean().sort_values(["adj_rand"], ascending=False).to_csv("dbscan_vs_kmeans.csv")

/var/folders/jq/lt0dyzf14y93d8k18k68_4fm0000gn/T/ipykernel_31550/2590128475.py:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  all_pipeline[(all_pipeline.remap == 0) & (all_pipeline.dbscan_eps == 0.4)].groupby(["clustering_method", "tf_idf_scale"]).mean().sort_values(["adj_rand"], ascending=False).to_csv("dbscan_vs_kmeans.csv")

In [13]:
!pwd

/Users/Rrando/Documents/GitHub/content-ml-experiments/tab_grouping/analysis

In [14]:
all_pipeline.columns

Index(['Unnamed: 0', 'history_scale', 'domain_scale', 'title_embedding_scale',
       'tf_idf_scale', 'clustering_method', 'dbscan_eps', 'remap',
       'num_cluster_method', 'text_for_embedding', 'embedding_model',
       'dataset', 'rand', 'adj_rand'],
      dtype='object')

In [16]:
all_pipeline.groupby("embedding_model").mean().sort_values(["adj_rand"], ascending=False)

/var/folders/jq/lt0dyzf14y93d8k18k68_4fm0000gn/T/ipykernel_31550/143489395.py:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  all_pipeline.groupby("embedding_model").mean().sort_values(["adj_rand"], ascending=False)

,Unnamed: 0,history_scale,domain_scale,title_embedding_scale,tf_idf_scale,dbscan_eps,remap,rand,adj_rand
embedding_model,,,,,,,,,
all-mpnet-base-v2,1367.5,0.0,0.0,1.0,0.15,0.4,6.666667,0.735767,0.313608
all-MiniLM-L6-v2,1319.5,0.0,0.0,1.0,0.15,0.4,6.666667,0.732232,0.282686

In [20]:
all_pipeline[(all_pipeline.remap == 5) & (all_pipeline.dbscan_eps == 0.4)].groupby(["embedding_model", "clustering_method", "tf_idf_scale"]).mean().sort_values(["adj_rand"], ascending=False)

/var/folders/jq/lt0dyzf14y93d8k18k68_4fm0000gn/T/ipykernel_31550/1002988956.py:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  all_pipeline[(all_pipeline.remap == 5) & (all_pipeline.dbscan_eps == 0.4)].groupby(["embedding_model", "clustering_method", "tf_idf_scale"]).mean().sort_values(["adj_rand"], ascending=False)

                                                  Unnamed: 0  history_scale  \
embedding_model   clustering_method tf_idf_scale
all-mpnet-base-v2 dbscan            0.3               1375.0            0.0
                                    0.0               1372.0            0.0
                  kmeans            0.3               1351.0            0.0
                  dbscan            0.1               1373.0            0.0
all-MiniLM-L6-v2  dbscan            0.3               1327.0            0.0
all-mpnet-base-v2 dbscan            0.2               1374.0            0.0
all-MiniLM-L6-v2  kmeans            0.2               1302.0            0.0
                  dbscan            0.0               1324.0            0.0
all-mpnet-base-v2 kmeans            0.2               1350.0            0.0
                                    0.1               1349.0            0.0
all-MiniLM-L6-v2  dbscan            0.2               1326.0            0.0
                                    0.1               1325.0            0.0
                  kmeans            0.0               1300.0            0.0
                                    0.1               1301.0            0.0
all-mpnet-base-v2 kmeans            0.0               1348.0            0.0
all-MiniLM-L6-v2  kmeans            0.3               1303.0            0.0

                                                  domain_scale  \
embedding_model   clustering_method tf_idf_scale
all-mpnet-base-v2 dbscan            0.3                    0.0
                                    0.0                    0.0
                  kmeans            0.3                    0.0
                  dbscan            0.1                    0.0
all-MiniLM-L6-v2  dbscan            0.3                    0.0
all-mpnet-base-v2 dbscan            0.2                    0.0
all-MiniLM-L6-v2  kmeans            0.2                    0.0
                  dbscan            0.0                    0.0
all-mpnet-base-v2 kmeans            0.2                    0.0
                                    0.1                    0.0
all-MiniLM-L6-v2  dbscan            0.2                    0.0
                                    0.1                    0.0
                  kmeans            0.0                    0.0
                                    0.1                    0.0
all-mpnet-base-v2 kmeans            0.0                    0.0
all-MiniLM-L6-v2  kmeans            0.3                    0.0

                                                  title_embedding_scale  \
embedding_model   clustering_method tf_idf_scale
all-mpnet-base-v2 dbscan            0.3                             1.0
                                    0.0                             1.0
                  kmeans            0.3                             1.0
                  dbscan            0.1                             1.0
all-MiniLM-L6-v2  dbscan            0.3                             1.0
all-mpnet-base-v2 dbscan            0.2                             1.0
all-MiniLM-L6-v2  kmeans            0.2                             1.0
                  dbscan            0.0                             1.0
all-mpnet-base-v2 kmeans            0.2                             1.0
                                    0.1                             1.0
all-MiniLM-L6-v2  dbscan            0.2                             1.0
                                    0.1                             1.0
                  kmeans            0.0                             1.0
                                    0.1                             1.0
all-mpnet-base-v2 kmeans            0.0                             1.0
all-MiniLM-L6-v2  kmeans            0.3                             1.0

                                                  dbscan_eps  remap      rand  \
embedding_model   clustering_method tf_idf_scale
all-mpnet-base-v2 dbscan            0.3                  0.4    5.0  0.803388
                                    0.0                  0.4    5.0  0.806528
                  kmeans            0.3                  0.4    5.0  0.738482
                  dbscan            0.1                  0.4    5.0  0.785225
all-MiniLM-L6-v2  dbscan            0.3                  0.4    5.0  0.786157
all-mpnet-base-v2 dbscan            0.2                  0.4    5.0  0.791262
all-MiniLM-L6-v2  kmeans            0.2                  0.4    5.0  0.738353
                  dbscan            0.0                  0.4    5.0  0.782228
all-mpnet-base-v2 kmeans            0.2                  0.4    5.0  0.726705
                                    0.1                  0.4    5.0  0.723921
all-MiniLM-L6-v2  dbscan            0.2                  0.4    5.0  0.780287
                                    0.1                  0.4    5.0  0.780699
                  kmeans            0.0                  0.4    5.0  0.725636
                                    0.1                  0.4    5.0  0.724745
all-mpnet-base-v2 kmeans            0.0                  0.4    5.0  0.700976
all-MiniLM-L6-v2  kmeans            0.3                  0.4    5.0  0.715058

                                                  adj_rand
embedding_model   clustering_method tf_idf_scale
all-mpnet-base-v2 dbscan            0.3           0.378215
                                    0.0           0.361670
                  kmeans            0.3           0.350927
                  dbscan            0.1           0.347258
all-MiniLM-L6-v2  dbscan            0.3           0.339895
all-mpnet-base-v2 dbscan            0.2           0.338977
all-MiniLM-L6-v2  kmeans            0.2           0.335513
                  dbscan            0.0           0.334127
all-mpnet-base-v2 kmeans            0.2           0.325811
                                    0.1           0.324468
all-MiniLM-L6-v2  dbscan            0.2           0.322664
                                    0.1           0.316355
                  kmeans            0.0           0.302768
                                    0.1           0.300673
all-mpnet-base-v2 kmeans            0.0           0.296830
all-MiniLM-L6-v2  kmeans            0.3           0.286528

In [5]:
!pwd

/Users/Rrando/Documents/GitHub/content-ml-experiments/tab_grouping/analysis

In [2]:
embed_test = pd.read_csv("../output/all_pipeline_embedding_test.csv", index_col=False)

In [15]:
embed_test.loc[embed_test.clustering_method == "dbscan", 'num_cluster_method'] = "none"

In [17]:
embed_test[(embed_test.remap == 0) & (embed_test.dbscan_eps == 0.4)].groupby(["embedding_model", "clustering_method", "num_cluster_method"]).mean().sort_values(["adj_rand"], ascending=False)

/var/folders/jq/lt0dyzf14y93d8k18k68_4fm0000gn/T/ipykernel_2593/190544645.py:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  embed_test[(embed_test.remap == 0) & (embed_test.dbscan_eps == 0.4)].groupby(["embedding_model", "clustering_method", "num_cluster_method"]).mean().sort_values(["adj_rand"], ascending=False)

                                                        Unnamed: 0  \
embedding_model   clustering_method num_cluster_method
all-mpnet-base-v2 kmeans            knee                     504.0
                  dbscan            none                     514.5
all-MiniLM-L6-v2  kmeans            silhouette               489.0
                                    knee                     486.0
all-mpnet-base-v2 kmeans            silhouette               507.0
all-MiniLM-L6-v2  dbscan            none                     496.5

                                                        history_scale  \
embedding_model   clustering_method num_cluster_method
all-mpnet-base-v2 kmeans            knee                          0.0
                  dbscan            none                          0.0
all-MiniLM-L6-v2  kmeans            silhouette                    0.0
                                    knee                          0.0
all-mpnet-base-v2 kmeans            silhouette                    0.0
all-MiniLM-L6-v2  dbscan            none                          0.0

                                                        domain_scale  \
embedding_model   clustering_method num_cluster_method
all-mpnet-base-v2 kmeans            knee                         0.0
                  dbscan            none                         0.0
all-MiniLM-L6-v2  kmeans            silhouette                   0.0
                                    knee                         0.0
all-mpnet-base-v2 kmeans            silhouette                   0.0
all-MiniLM-L6-v2  dbscan            none                         0.0

                                                        title_embedding_scale  \
embedding_model   clustering_method num_cluster_method
all-mpnet-base-v2 kmeans            knee                                  1.0
                  dbscan            none                                  1.0
all-MiniLM-L6-v2  kmeans            silhouette                            1.0
                                    knee                                  1.0
all-mpnet-base-v2 kmeans            silhouette                            1.0
all-MiniLM-L6-v2  dbscan            none                                  1.0

                                                        tf_idf_scale  \
embedding_model   clustering_method num_cluster_method
all-mpnet-base-v2 kmeans            knee                         0.0
                  dbscan            none                         0.0
all-MiniLM-L6-v2  kmeans            silhouette                   0.0
                                    knee                         0.0
all-mpnet-base-v2 kmeans            silhouette                   0.0
all-MiniLM-L6-v2  dbscan            none                         0.0

                                                        dbscan_eps  remap  \
embedding_model   clustering_method num_cluster_method
all-mpnet-base-v2 kmeans            knee                       0.4    0.0
                  dbscan            none                       0.4    0.0
all-MiniLM-L6-v2  kmeans            silhouette                 0.4    0.0
                                    knee                       0.4    0.0
all-mpnet-base-v2 kmeans            silhouette                 0.4    0.0
all-MiniLM-L6-v2  dbscan            none                       0.4    0.0

                                                            rand  adj_rand
embedding_model   clustering_method num_cluster_method
all-mpnet-base-v2 kmeans            knee                0.726403  0.290479
                  dbscan            none                0.699151  0.270600
all-MiniLM-L6-v2  kmeans            silhouette          0.754944  0.265861
                                    knee                0.728406  0.254920
all-mpnet-base-v2 kmeans            silhouette          0.726056  0.253460
all-MiniLM-L6-v2  dbscan            none                0.675739  0.240188